### PR TITLE
Migrated to Swift 3.0, fixed issues with algorithm, added tests

### PR DESCRIPTION
**Pull request by DarkSatyr**

### CODE REVIEW

**Comment by cliffremote** [comment]
The code should've already been for Swift 3. Swift 2 was a previous commit. Is this what you wanted to do? Thanks for helping out, to be sure.

**Comment by DarkSatyr** [comment]
Previous Swift code version was 2.0 or 2.1 at least. I've just converted it to 2.2 since it doesn't compile was newest Xcode (7.3.1) when Apple release Xcode 8 with Swift 3.0 then we can convert to it

**Comment by cliffordh** [comment]
With the release of Swift 3.0 can you apply your fixes to the algorithm to the master branch.

**Comment by DarkSatyr** [comment]
Migrated to Swift 3.0

**Pull request merged**
